config/routes.rb
Rails.application.routes.draw do
  
  get 'top' => 'homes#top'
  # get 'new' => 'books#new'
  # post 'books' => 'books#create'
  # get 'books' => 'books#index'
  # get 'books/:id' => 'books#show'
  # patch 'books/:id' => 'books#update'
  # get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  
  resources :books
  root to: 'homes#top'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: "Book was successfully updated."
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id]) 
    book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book do |f| %>

  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved: %>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  
  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>
  
  <p><%= f.submit 'Update Book' %></p>

<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<header>
  <h1> Books </h1>
</header>

<div class="book-wrap">
<table> 
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @books.each do |book| %>
  <div class="book-box">
    
    <tr>
      <td><span class="book-title"><%= book.title %></span></td>
      <td><span class="book-body"><%= book.body %></span></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
    
  </div>
    <% end %>
  </tbody>

</table>
</div>

<h2>New book</h2>

<%= form_with model: @book, method: :post do |f| %>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Body</h4>
  <%= f.text_area :body %>
	
	<h4></h4>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= form_with model: @book, url: '/book', method: :post do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Body</h4>
  <%= f.text_area :body %>
	
	<h4></h4>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<!--<h2>Editing Book</h2>-->
<!--<p><%= @book.title %></p>-->

<p>Title: <%= @book.title %></p>

<p>Body: <%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<%= link_to 'start' ,books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <div>
      <%= flash[:notice] %>
    </div>

    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <!--<header>-->
    <!--  <h1> Books </h1>-->
    <!--</header>-->
    
    <!--<nav>-->
    <!--  <table>-->
    <!--    <tr>-->
    <!--      <ul class="nav-book">-->
            
    <!--        <th>Title</th>-->
    <!--        <th>Body</th>-->
    <!--        <th></th>-->
            <!--<li class="nav-book-item">-->
            <!--  <%= link_to "Top", top_path %>-->
            <!--</li>-->
            <!--<li class="nav-book-item">-->
            <!--  <%= link_to "Books", books_path %>-->
            <!--</li>-->
            <!--<li class="nav-book-item">-->
            <!--  <%= link_to "New Book", new_book_path %>-->
            <!--</li>-->
    <!--      </ul>-->
    <!--    </tr>-->
    <!--  </table>-->
    <!--</nav>-->
    
    <main>
      <%= yield %>
    </main>
    
  </body>
</html>